In [2]:
import pandas as pd
from scipy.stats import mode
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

Obtener los Datos

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
iris_df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                      columns= iris['feature_names'] + ['target'])
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0.0
1,4.9,3.0,1.4,0.2,0.0
2,4.7,3.2,1.3,0.2,0.0
3,4.6,3.1,1.5,0.2,0.0
4,5.0,3.6,1.4,0.2,0.0

Separar *X* de *y*

In [5]:
X=iris_df[["sepal length (cm)", "sepal width (cm)", "petal length (cm)", "petal width (cm)"]]
X

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
y=iris_df[["target"]]
y

     target
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
..      ...
145     2.0
146     2.0
147     2.0
148     2.0
149     2.0

[150 rows x 1 columns]

CÃºales son las X?

sepal and petal lenght and width

CuÃ¡l es la y?

target

Separar en conjuntos de entrenamiento y prueba

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y,
                                                   test_size= 0.33,
                                                   shuffle= True, #aleatorizar los datos
                                                   random_state= 0)

Construir el modelo

In [8]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)

In [9]:
neigh.fit(X_train, y_train.values.ravel())

KNeighborsClassifier(n_neighbors=3)

Comparar los resultados en el conjunto de prueba

In [10]:
y_test["prediccion"]=neigh.predict(X_test)
y_test

     target  prediccion
114     2.0         2.0
62      1.0         1.0
33      0.0         0.0
107     2.0         2.0
7       0.0         0.0
100     2.0         2.0
40      0.0         0.0
86      1.0         1.0
76      1.0         1.0
71      1.0         1.0
134     2.0         2.0
51      1.0         1.0
73      1.0         1.0
54      1.0         1.0
63      1.0         1.0
37      0.0         0.0
78      1.0         1.0
90      1.0         1.0
45      0.0         0.0
16      0.0         0.0
121     2.0         2.0
66      1.0         1.0
24      0.0         0.0
8       0.0         0.0
126     2.0         2.0
22      0.0         0.0
44      0.0         0.0
97      1.0         1.0
93      1.0         1.0
26      0.0         0.0
137     2.0         2.0
84      1.0         1.0
27      0.0         0.0
127     2.0         2.0
132     2.0         2.0
59      1.0         1.0
18      0.0         0.0
83      1.0         2.0
61      1.0         1.0
92      1.0         1.0
112     2.0         2.0
2       0.0         0.0
141     2.0         2.0
43      0.0         0.0
10      0.0         0.0
60      1.0         1.0
116     2.0         2.0
144     2.0         2.0
119     2.0         1.0
108     2.0         2.0

Obtener las probabilidades de pertenencia por clase [0, 1, o 2]

In [11]:
neigh.predict_proba(X_test)

array([[0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.66666667, 0.33333333],
       [1.        , 0.        , 0.        ],
       [0.        , 0.66666667, 0.33333333],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.66666667],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.66666667, 0.33333333],
       [0.        , 0.        , 1.        ]])